name             'mytestfinal'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures mytestfinal'
long_description 'Installs/Configures mytestfinal'
version          '0.1.0'
