driver_plugin: docker
driver_config:
  require_chef_omnibus: true
provisioner: chef_zero

platforms:
- name: centos
  driver_config:
    image: "chefimage"
    platform: "rhel"
- name: ubuntu
  driver_config:
    image: "ubuntu"
    plateform: "ubuntu"
    network:
    - ["private_network", {ip: "33.33.33.10"}]

suites:
  - name: source 
    run_list:
      - recipe[mytestfinal::default]

