---
driver:
 name: docker
driver_config:
 require_chef_omnibus: false
 remove_images: true

provisioner:
 name: chef_zero

platforms:
  - name: centos
    driver_config:
      image: "centos6-chef"
suites:
  name: default
  run_list:
    - "recipe[test]"