---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
- name: chef_centos
  driver:
    image: chef_centos:latest
    platform: rhel

suites:
  - name: default
    run_list:
      - recipe[weblogic::default]
    attributes:
